21/Mar/2024 11:24:28 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
21/Mar/2024 11:24:28 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:02:40 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:02:40 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:03:43 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:03:43 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:07:12 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:07:12 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:07:42 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:07:42 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:14:04 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:14:04 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:17:05 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:17:05 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:43:47 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:43:47 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:46:22 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:46:22 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:51:56 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:51:56 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:52:41 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 11:52:41 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 11:52:41 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:52:41 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:55:45 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:55:45 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:56:05 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 11:56:05 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:53:00 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:53:00 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:54:23 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:54:23 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:57:06 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:57:06 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:57:12 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 12:57:12 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 12:57:12 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 12:57:12 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:06:41 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:06:41 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:06:52 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 13:06:52 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 13:06:52 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:06:52 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:10:37 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:10:37 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:11:01 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 13:11:01 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:02:13 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:02:13 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:03:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:03:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:03:49 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:03:49 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:03:56 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:03:56 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:26 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:04:26 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:04:26 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:26 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:32 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:32 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:57 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:04:57 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/autheSys/settings.py changed, reloading.
22/Mar/2024 17:04:58 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:04:58 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:05:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:05:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:05:49 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:05:49 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:07:22 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:07:22 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:07:22 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:07:22 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:13:54 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:13:54 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:13:54 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:13:54 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:14:13 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
22/Mar/2024 17:14:13 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
22/Mar/2024 17:14:14 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:14:14 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:15:10 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:15:10 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:15:11 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:15:11 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:16:00 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:16:00 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
22/Mar/2024 17:16:00 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:16:00 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:16:25 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:16:25 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:16:25 (ERROR)- django.server- "GET / HTTP/1.1" 500 62358
22/Mar/2024 17:16:25 (ERROR)- django.server- "GET / HTTP/1.1" 500 62358
22/Mar/2024 17:16:25 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:16:25 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:16:25 (ERROR)- django.server- "GET / HTTP/1.1" 500 62084
22/Mar/2024 17:16:25 (ERROR)- django.server- "GET / HTTP/1.1" 500 62084
22/Mar/2024 17:27:27 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:27:27 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:27:37 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:27:37 (ERROR)- django.request- Internal Server Error: /
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/middleware/clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
22/Mar/2024 17:27:37 (ERROR)- django.server- "GET / HTTP/1.1" 500 62221
22/Mar/2024 17:27:37 (ERROR)- django.server- "GET / HTTP/1.1" 500 62221
22/Mar/2024 17:28:45 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
22/Mar/2024 17:28:45 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
22/Mar/2024 17:28:45 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:28:45 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
22/Mar/2024 17:28:49 (INFO)- django.server- "GET / HTTP/1.1" 200 1422
22/Mar/2024 17:28:49 (INFO)- django.server- "GET / HTTP/1.1" 200 1422
22/Mar/2024 17:30:10 (INFO)- django.server- "GET / HTTP/1.1" 200 1420
22/Mar/2024 17:30:10 (INFO)- django.server- "GET / HTTP/1.1" 200 1420
23/Mar/2024 10:45:32 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:45:32 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:48:33 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:48:33 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:51:04 (WARNING)- django.request- Bad Request: /api/register
23/Mar/2024 10:51:04 (WARNING)- django.request- Bad Request: /api/register
23/Mar/2024 10:51:04 (WARNING)- django.server- "POST /api/register HTTP/1.1" 400 78
23/Mar/2024 10:51:04 (WARNING)- django.server- "POST /api/register HTTP/1.1" 400 78
23/Mar/2024 10:52:38 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
23/Mar/2024 10:52:38 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
23/Mar/2024 10:52:39 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:52:39 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:52:45 (ERROR)- django.request- Internal Server Error: /api/register
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jatinkoli/Desktop/Codes/autheSys/users/views.py", line 10, in post
    seralizer.is_valid(raise_exception=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `passwordn` is not valid for model `User`.
23/Mar/2024 10:52:45 (ERROR)- django.request- Internal Server Error: /api/register
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jatinkoli/Desktop/Codes/autheSys/users/views.py", line 10, in post
    seralizer.is_valid(raise_exception=True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 479, in to_internal_value
    for field in fields:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `passwordn` is not valid for model `User`.
23/Mar/2024 10:52:45 (ERROR)- django.server- "POST /api/register HTTP/1.1" 500 133026
23/Mar/2024 10:52:45 (ERROR)- django.server- "POST /api/register HTTP/1.1" 500 133026
23/Mar/2024 10:53:35 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/serializers.py changed, reloading.
23/Mar/2024 10:53:35 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/serializers.py changed, reloading.
23/Mar/2024 10:53:36 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:53:36 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
23/Mar/2024 10:53:47 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 45
23/Mar/2024 10:53:47 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 45
23/Mar/2024 10:54:22 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 47
23/Mar/2024 10:54:22 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 47
24/Mar/2024 06:50:07 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 06:50:07 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 06:50:14 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 53
24/Mar/2024 06:50:14 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 53
24/Mar/2024 06:50:30 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 49
24/Mar/2024 06:50:30 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 49
24/Mar/2024 06:50:44 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 49
24/Mar/2024 06:50:44 (INFO)- django.server- "POST /api/register HTTP/1.1" 200 49
24/Mar/2024 08:13:44 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:13:44 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:14:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
24/Mar/2024 08:14:49 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/urls.py changed, reloading.
24/Mar/2024 08:14:50 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:14:50 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:15:14 (ERROR)- django.request- Internal Server Error: /api/login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jatinkoli/Desktop/Codes/autheSys/users/views.py", line 21, in post
    email = request.data['email']
            ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'
24/Mar/2024 08:15:14 (ERROR)- django.request- Internal Server Error: /api/login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jatinkoli/Desktop/Codes/autheSys/users/views.py", line 21, in post
    email = request.data['email']
            ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'email'
24/Mar/2024 08:15:14 (ERROR)- django.server- "POST /api/login HTTP/1.1" 500 86864
24/Mar/2024 08:15:14 (ERROR)- django.server- "POST /api/login HTTP/1.1" 500 86864
24/Mar/2024 08:16:14 (ERROR)- __name__- Password didn't matched !
NoneType: None
24/Mar/2024 08:16:14 (WARNING)- django.request- Forbidden: /api/login
24/Mar/2024 08:16:14 (WARNING)- django.request- Forbidden: /api/login
24/Mar/2024 08:16:14 (WARNING)- django.server- "POST /api/login HTTP/1.1" 403 38
24/Mar/2024 08:16:14 (WARNING)- django.server- "POST /api/login HTTP/1.1" 403 38
24/Mar/2024 08:17:31 (ERROR)- __name__- Password didn't matched !
NoneType: None
24/Mar/2024 08:17:31 (WARNING)- django.request- Forbidden: /api/login
24/Mar/2024 08:17:31 (WARNING)- django.request- Forbidden: /api/login
24/Mar/2024 08:17:31 (WARNING)- django.server- "POST /api/login HTTP/1.1" 403 38
24/Mar/2024 08:17:31 (WARNING)- django.server- "POST /api/login HTTP/1.1" 403 38
24/Mar/2024 08:17:37 (INFO)- django.server- "POST /api/login HTTP/1.1" 200 33
24/Mar/2024 08:17:37 (INFO)- django.server- "POST /api/login HTTP/1.1" 200 33
24/Mar/2024 08:18:25 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 08:18:25 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 08:18:25 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:18:25 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:18:41 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 08:18:41 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 08:18:42 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:18:42 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:50:09 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:50:09 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:50:21 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 08:50:21 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:10:14 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:10:14 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:21:54 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:21:54 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:22:37 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 09:22:37 (INFO)- django.utils.autoreload- /Users/jatinkoli/Desktop/Codes/autheSys/users/views.py changed, reloading.
24/Mar/2024 09:22:38 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
24/Mar/2024 09:22:38 (INFO)- django.utils.autoreload- Watching for file changes with StatReloader
